version: "3"

services:
  # Database Server
  postgis:
    image: postgis/postgis:15-3.3
    container_name: postgis
    restart: always
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_DB: temp
      POSTGRES_USER: temp
      POSTGRES_PASSWORD: temp
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgis:/var/lib/postgresql


volumes:
  media:
    external: false
  postgis:
    external: false