version: "3"

services:
  # Database Server
  postgis:
    image: postgis/postgis:15-3.3
    container_name: postgis
    restart: always
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_DB: temp
      POSTGRES_USER: temp
      POSTGRES_PASSWORD: temp
    ports:
      - "5432:5432"
    volumes:
      - postgis:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend Server
  backendchallenge:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: backendchallenge
    restart: always
    ports:
      - 8000:8000
    environment:
      - DEBUG=True
      - DB_DATABASE=temp
      - DB_USERNAME=temp
      - DB_PASSWORD=temp
      - DB_HOST=postgis
      - DB_PORT=5432
      - GUNICORN_SSL=false
    volumes:
      - media:/app/media
    depends_on:
      postgis:
          condition: service_healthy

volumes:
  media:
    external: false
  postgis:
    external: false